version: "3.8"
services:
  local-stack:
    image: localstack/localstack:latest
    container_name: localstack
    volumes:
      - ./src/resources/split_data:/opt/code/localstack/split_data
    ports:
      - "4566:4566"
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    depends_on:
      - local-stack
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - ./infra:/infra
      - ./scripts:/scripts
      - ./src:/src
    entrypoint: /scripts/terraform_commands.sh
