FROM python:3.9-slim-buster

RUN apt-get update -y
RUN apt-get install libpq-dev -y
RUN apt-get install gcc -y
RUN apt-get install wget -y 
RUN apt-get install unzip -y
RUN wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
RUN unzip terraform_1.3.7_linux_amd64.zip
RUN mv terraform /usr/local/bin/

COPY ./scripts/terraform/commands.sh /scripts/commands.sh
COPY ./src /src
COPY ./infra /infra