version: "3.8"
services:
  graph-project-local-stack:
    image: graph-project-local-stack
    container_name: graph-project-local-stack
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy

  graph-project-terraform-python:
    image: graph-project-terraform-python
    container_name: graph-project-terraform-python
    depends_on:
      - graph-project-local-stack
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    entrypoint: /scripts/commands.sh

  graph-project-postgres:
    image: graph-project-postgres
    container_name: graph-project-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PROJECT_DATABASE_NAME=graph_project
    depends_on:
      - graph-project-local-stack
    ports:
      - "5432:5432"
